language: cpp

compiler:
  - gcc

dist: bionic

cache:
  apt: true

branches:
  only:
    - master

before_install:
  - pip install --user cpp-coveralls codecov
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends lcov bzip2 wget cmake make g++ xsdcxx 
  - sudo apt-get install -y --no-install-recommends libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-thread-dev libboost-program-options-dev
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt-get update
  - sudo apt-get install -y intel-mkl-64bit-2018.3-051
#  - bash resources/install_dynadjust_prerequisites.sh -m 1

script:
   - cd ..
   - cp ./DynAdjust/resources/make_dynadjust_gcc.sh ./
   - bash make_dynadjust_gcc.sh --no-install --auto --do-not-clone --test
  
after_success:
   - cd ./DynAdjust/dynadjust/
#  - coveralls --root . -E ".*CMakeFiles.*" 
#  - coveralls --root . --verbose --exclude-pattern ".*feature_tests.*" --exclude-pattern ".*CompilerId.*" --gcov-options '\-lp'
   - coveralls 
     --gcov /usr/bin/gcov
     --exclude-pattern ".*feature_tests.*" 
     --exclude-pattern ".*CompilerId.*" 
     --exclude-pattern ".*/resources/.*"
     --gcov-options '\-lp' >/dev/null 2>&1
   - bash <(curl -s https://codecov.io/bash) >/dev/null 2>&1
