language: cpp

compiler:
  - gcc

dist: bionic

cache:
  apt: true

branches:
  only:
    - master

before_install:
  - pip install --user cpp-coveralls codecov
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends lcov bzip2 wget cmake make g++ xsdcxx libxerces-c-dev
  - sudo apt-get install -y --no-install-recommends libboost-system-dev libboost-filesystem-dev libboost-timer-dev libboost-thread-dev libboost-program-options-dev
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
  - sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
  - sudo apt-get update
  - sudo apt-get install -y intel-basekit

script:
   - chmod +x ./resources/make_dynadjust_gcc.sh
   - ./resources/make_dynadjust_gcc.sh --no-install --auto --no-clone --test
  
after_success:
   - cd ./dynadjust/
   - coveralls 
     --gcov /usr/bin/gcov
     --exclude-pattern ".*feature_tests.*" 
     --exclude-pattern ".*CompilerId.*" 
     --exclude-pattern ".*/resources/.*"
     --gcov-options '\-lp' >/dev/null 2>&1
   - bash <(curl -s https://codecov.io/bash) >/dev/null 2>&1
