// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include <include/exception/dnaexception.hpp>
#include <include/parameters/dnaepsg.hpp>
#include <dynadjust/dnaimport/dnaparser_pimpl.hxx>
#include <dynadjust/dnaimport/dnaparser_validators.hpp>
#include <include/measurement_types/dnastntally.hpp>

using namespace dynadjust::measurements;
using namespace dynadjust::epsg;
using namespace dynadjust::exception;
using namespace dynadjust::import;

extern MsrTally g_parsemsr_tally;
extern StnTally g_parsestn_tally;
extern UINT32 g_fileOrder;

// Clusterpoint_pimpl
//

void Clusterpoint_pimpl::pre()
{
	_dnaGpsPoint.reset(new CDnaGpsPoint);
	// The following is needed so that SetX and SetY can properly handle
	// latitude|X and longitude|Y
	_dnaGpsPoint->SetType(_parent_dnaGpsPointCluster->GetType());
	_dnaGpsPoint->SetCoordType(_parent_dnaGpsPointCluster->GetCoordType());
	_dnaGpsPoint->SetFirst(_parent_dnaGpsPointCluster->GetFirst());
	_dnaGpsPoint->SetClusterID(_parent_dnaGpsPointCluster->GetClusterID());
	
	_dnaGpsPoint->SetReferenceFrame(_parent_dnaGpsPointCluster->GetReferenceFrame());
	_dnaGpsPoint->SetEpoch(_parent_dnaGpsPointCluster->GetEpoch()); 
		
	_dnaGpsPoint->SetClusterDBID(
		_parent_dnaGpsPointCluster->GetClusterDBID(),
		_parent_dnaGpsPointCluster->GetClusterDBIDset());

}

void Clusterpoint_pimpl::X (const ::std::string& X)
{
	_dnaGpsPoint->SetX(X);

	// increment measurement counter
	*(_pMeasurementCount) += 1;
	g_parsemsr_tally.Y++;
}

void Clusterpoint_pimpl::Y (const ::std::string& Y)
{
	_dnaGpsPoint->SetY(Y);

	// increment measurement counter
	*(_pMeasurementCount) += 1;
	g_parsemsr_tally.Y++;
}

void Clusterpoint_pimpl::Z (const ::std::string& Z)
{
	_dnaGpsPoint->SetZ(Z);

	// increment measurement counter
	*(_pMeasurementCount) += 1;
	g_parsemsr_tally.Y++;
}

void Clusterpoint_pimpl::MeasurementDBID(const ::std::string& MeasurementID)
{
	_dnaGpsPoint->SetMeasurementDBID(MeasurementID);
}


void Clusterpoint_pimpl::SigmaXX (const ::std::string& SigmaXX)
{
	_dnaGpsPoint->SetSigmaXX(SigmaXX);
}

void Clusterpoint_pimpl::SigmaXY (const ::std::string& SigmaXY)
{
	_dnaGpsPoint->SetSigmaXY(SigmaXY);
}

void Clusterpoint_pimpl::SigmaXZ (const ::std::string& SigmaXZ)
{
	_dnaGpsPoint->SetSigmaXZ(SigmaXZ);
}

void Clusterpoint_pimpl::SigmaYY(const ::std::string& SigmaYY)
{
	_dnaGpsPoint->SetSigmaYY(SigmaYY);
}

void Clusterpoint_pimpl::SigmaYZ(const ::std::string& SigmaYZ)
{
	_dnaGpsPoint->SetSigmaYZ(SigmaYZ);
}

void Clusterpoint_pimpl::SigmaZZ(const ::std::string& SigmaZZ)
{
	_dnaGpsPoint->SetSigmaZZ(SigmaZZ);
}

void Clusterpoint_pimpl::PointCovariance ()
{
}

void Clusterpoint_pimpl::post_Clusterpoint ()
{
	if (_dnaGpsPoint && _parent_dnaGpsPointCluster)
		_parent_dnaGpsPointCluster->AddGpsPoint(_dnaGpsPoint.get());
}

// Directions_pimpl
//

void Directions_pimpl::pre()
{
	_dnaDirection.reset(new CDnaDirection);
	_dnaDirection->SetClusterID(_parent_dnaDirectionSet->GetClusterID());

	_dnaDirection->SetClusterDBID(
		_parent_dnaDirectionSet->GetClusterDBID(),
		_parent_dnaDirectionSet->GetClusterDBIDset());
}

void Directions_pimpl::Ignore(const ::std::string& Ignore)
{
	if (Ignore.empty())
		_dnaDirection->SetIgnore(false);
	else
		_dnaDirection->SetIgnore(true);
}

void Directions_pimpl::Target(const ::std::string& Target)
{
	_dnaDirection->SetTarget(Target);
}

void Directions_pimpl::Value(const ::std::string& Value)
{
	_dnaDirection->SetValue(Value);

	//if (_dnaDirection->NotIgnored())
	//{
		// increment measurement counter
		*(_pMeasurementCount) += 1;
	//}
}

void Directions_pimpl::StdDev(const ::std::string& StdDev)
{
	_dnaDirection->SetStdDev(StdDev);

}
	

void Directions_pimpl::MeasurementDBID(const ::std::string& MeasurementID)
{
	_dnaDirection->SetMeasurementDBID(MeasurementID);
}
	

void Directions_pimpl::post_Directions(const UINT32& total)
{
	if (!_parent_dnaDirectionSet)
		return;

	// Always add the direction to the set
	_parent_dnaDirectionSet->AddDirection(_dnaDirection.get());

	// If the parent is ignored, nothing more to check
	if (_parent_dnaDirectionSet->GetIgnore())
		return;

	// Count non-ignored directions for the tally
	if (_dnaDirection->NotIgnored())
	{
		g_parsemsr_tally.D++;
		return;
	}

	// Direction is ignored — validate this doesn't leave the set empty
	ValidateDirectionInSet(_parent_dnaDirectionSet,
		true, total);
}

// DnaMeasurement_pimpl
//

void DnaMeasurement_pimpl::pre()
{
	_dnaCurrentMsr.reset();

	// Initialise flags that will track whether Reference frame has been supplied
	_ReferenceframeTagSupplied = false;
	_EpochTagSupplied = false;
}


void DnaMeasurement_pimpl::Type(const ::std::string& Type)
{
	char cType = ValidateMeasurementType(Type);

	std::string frame, epoch;

	if (_ReferenceframeTagSupplied || _overridereferenceframe)
		frame = _referenceframe;
	else
		frame = datumFromEpsgString(_fileEpsg);

	if (_EpochTagSupplied || _overridereferenceframe)
		epoch = _epoch;
	else
		epoch = _fileEpoch;

	_dnaCurrentMsr = CreateMeasurement(cType, _pclusterID,
		*(_pMeasurementCount), g_parsemsr_tally, frame, epoch);
	_dnaCurrentMsr->SetType(Type);
}

void DnaMeasurement_pimpl::Ignore(const ::std::string& Ignore)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	if (Ignore.empty())
		_dnaCurrentMsr->SetIgnore(false);
	else
	{
		_dnaCurrentMsr->SetIgnore(true);
		g_parsemsr_tally.ignored++;
	}
}

void DnaMeasurement_pimpl::First(const ::std::string& First)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateFirst(First);
	_dnaCurrentMsr->SetFirst(First);
}

void DnaMeasurement_pimpl::Second(const ::std::string& Second)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateSecond(Second, _dnaCurrentMsr->GetTypeC(), _dnaCurrentMsr->GetFirst());
	if (TypeRequiresSecond(_dnaCurrentMsr->GetTypeC()))
		_dnaCurrentMsr->SetTarget(Second);
}

void DnaMeasurement_pimpl::Third(const ::std::string& Third)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateThird(Third, _dnaCurrentMsr->GetTypeC(), _dnaCurrentMsr->GetFirst());
	_dnaCurrentMsr->SetTarget2(Third);
}

void DnaMeasurement_pimpl::Value(const ::std::string& Value)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateValue(Value, _dnaCurrentMsr->GetTypeC(), _dnaCurrentMsr->GetFirst());
	_dnaCurrentMsr->SetValue(Value);
}

void DnaMeasurement_pimpl::StdDev(const ::std::string& StdDev)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateStdDev(StdDev, _dnaCurrentMsr->GetTypeC(), _dnaCurrentMsr->GetFirst());
	_dnaCurrentMsr->SetStdDev(StdDev);
}

void DnaMeasurement_pimpl::InstHeight(const ::std::string& InstHeight)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	// Instrument and target heights only make sense for 
	// slope distances, vertical angles and zenith distances.
	// Don't need instrument height for all other types.
	switch (_dnaCurrentMsr->GetTypeC()) {
	case 'S':
	case 'V':
	case 'Z':
		_dnaCurrentMsr->SetInstrumentHeight(InstHeight);
		break;
	}
}

void DnaMeasurement_pimpl::TargHeight(const ::std::string& TargHeight)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	// Instrument and target heights only make sense for 
	// slope distances, vertical angles and zenith distances.
	// Don't need instrument height for all other types.
	switch (_dnaCurrentMsr->GetTypeC()) {
	case 'S':
	case 'V':
	case 'Z':
		_dnaCurrentMsr->SetTargetHeight(TargHeight);
		break;
	}
}

void DnaMeasurement_pimpl::Total(const ::std::string& Total)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	ValidateTotal(Total, _dnaCurrentMsr->GetTypeC());
	_dnaCurrentMsr->SetTotal(Total);
	_total = LongFromString<UINT32>(Total);
}

void DnaMeasurement_pimpl::Directions()
{
}

void DnaMeasurement_pimpl::Vscale(const ::std::string& Vscale)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	_dnaCurrentMsr->SetVscale(DefaultScale(Vscale));
}

void DnaMeasurement_pimpl::Epoch(const ::std::string& Epoch)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	try
	{
		// Override the reference frame with the user specified frame?
		if (_overridereferenceframe)
		{
			_dnaCurrentMsr->SetEpoch(_epoch);
			return;
		}

		if (Epoch.empty())
			// Do nothing - use default epoch
			return;

		_dnaCurrentMsr->SetEpoch(Epoch);
		_EpochTagSupplied = true;
	}
	catch (const std::runtime_error& e) {
		std::stringstream ss("");
		ss << e.what();
		ss << "    - Measurement type: " << _dnaCurrentMsr->GetType() << std::endl <<
			"    - From:             " << _dnaCurrentMsr->GetFirst() << std::endl <<
			"    - To:               " << _dnaCurrentMsr->GetTarget() << std::endl <<
			"    - Reference frame:  " << _dnaCurrentMsr->GetReferenceFrame() << std::endl <<
			"    - Epoch:            " << Epoch << std::endl;
		throw XMLInteropException(ss.str(), 0);
	}
}

void DnaMeasurement_pimpl::EpochOfObservation(const ::std::string& EpochOfObservation)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	try
	{
		if (EpochOfObservation.empty())
			return;

		_dnaCurrentMsr->SetObservationEpoch(EpochOfObservation);
	}
	catch (const std::runtime_error& e) {
		std::stringstream ss("");
		ss << e.what();
		ss << "    - Measurement type:    " << _dnaCurrentMsr->GetType() << std::endl <<
			"    - From:                " << _dnaCurrentMsr->GetFirst() << std::endl <<
			"    - To:                  " << _dnaCurrentMsr->GetTarget() << std::endl <<
			"    - Reference frame:     " << _dnaCurrentMsr->GetReferenceFrame() << std::endl <<
			"    - Epoch of observation: " << EpochOfObservation << std::endl;
		throw XMLInteropException(ss.str(), 0);
	}
}

void DnaMeasurement_pimpl::ReferenceFrame(const ::std::string& ReferenceFrame)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	try
	{
		// Set the reference frame found for this measurement
		_dnaCurrentMsr->SetReferenceFrame(ReferenceFrame);

		// Override the reference frame with the user specified frame?
		if (_overridereferenceframe)
		{
			_dnaCurrentMsr->SetReferenceFrame(_referenceframe);
			return;
		}

		// Was no frame supplied?  If so, do nothing (use default reference frame)
		if (ReferenceFrame.empty())
			return;

		// Set the reference frame found for this measurement
		_dnaCurrentMsr->SetReferenceFrame(ReferenceFrame);
		_ReferenceframeTagSupplied = true;
	}
	catch (const std::runtime_error& e) {
		std::stringstream ss("");
		ss << e.what();
		ss << "    - Measurement type: " << _dnaCurrentMsr->GetType() << std::endl <<
			"    - From:             " << _dnaCurrentMsr->GetFirst() << std::endl <<
			"    - To:               " << _dnaCurrentMsr->GetTarget() << std::endl <<
			"    - Reference frame:  " << ReferenceFrame << std::endl <<
			"    - Epoch:            " << _dnaCurrentMsr->GetEpoch() << std::endl;
		throw XMLInteropException(ss.str(), 0);
	}
}

void DnaMeasurement_pimpl::GPSBaseline()
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
}


void DnaMeasurement_pimpl::Hscale(const ::std::string& Hscale)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	_dnaCurrentMsr->SetHscale(DefaultScale(Hscale));
}


void DnaMeasurement_pimpl::Lscale(const ::std::string& Lscale)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	_dnaCurrentMsr->SetLscale(DefaultScale(Lscale));
}


void DnaMeasurement_pimpl::Pscale(const ::std::string& Pscale)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	_dnaCurrentMsr->SetPscale(DefaultScale(Pscale));
}


void DnaMeasurement_pimpl::Clusterpoint()
{
}

void DnaMeasurement_pimpl::Coords(const ::std::string& Coords)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	_dnaCurrentMsr->SetCoordType(Coords);
}


void DnaMeasurement_pimpl::Source(const ::std::string& Source)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	if (Source.empty())
		_dnaCurrentMsr->SetSource("");
	else
		_dnaCurrentMsr->SetSource(Source);
}
	

void DnaMeasurement_pimpl::MeasurementDBID(const ::std::string& MeasurementID)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	if (MeasurementID.empty())
		_dnaCurrentMsr->SetMeasurementDBID("");
	else
		_dnaCurrentMsr->SetMeasurementDBID(MeasurementID);
}
	

void DnaMeasurement_pimpl::ClusterDBID(const ::std::string& ClusterID)
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	if (ClusterID.empty())
		_dnaCurrentMsr->SetClusterDBID("");
	else
		_dnaCurrentMsr->SetClusterDBID(ClusterID);
}
	

void DnaMeasurement_pimpl::post_DnaMeasurement()
{
	if (!_dnaCurrentMsr)
		throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);

	// Ignored empty direction set — skip silently
	if (_dnaCurrentMsr->GetTypeC() == 'D' &&
		_dnaCurrentMsr->GetTotal() == 0 && _dnaCurrentMsr->GetIgnore())
		return;

	_vParentMsrs->push_back(_dnaCurrentMsr);
	FinaliseMeasurement(_dnaCurrentMsr, _preferSingleXasG);
}

// DnaStation_pimpl
//

void DnaStation_pimpl::pre()
{
	std::string frame, epoch;

	if (_overridereferenceframe)
		frame = _referenceframe;
	else
		frame = datumFromEpsgString(_fileEpsg);

	if (_overridereferenceframe)
		epoch = _epoch;
	else
		epoch = _fileEpoch;

	_dnaCurrentStn.reset(new CDnaStation(frame, epoch));
	_dnaCurrentStn->SetfileOrder(g_fileOrder++);
}

void DnaStation_pimpl::Name(const ::std::string& Name)
{
	ValidateStationName(Name);
	_dnaCurrentStn->SetName(Name);
}


void DnaStation_pimpl::Constraints(const ::std::string& Constraints)
{
	std::string c = DefaultConstraints(Constraints);
	_dnaCurrentStn->SetConstraints(c);
	g_parsestn_tally.addstation(c);
}


void DnaStation_pimpl::Type(const ::std::string& Type)
{
	_dnaCurrentStn->SetCoordType(Type);
}

void DnaStation_pimpl::StationCoord()
{
}

void DnaStation_pimpl::Description(const ::std::string& Description)
{
	_dnaCurrentStn->SetDescription(SanitiseDescription(Description));
}

void DnaStation_pimpl::post_DnaStation()
{
	_vParentStns->push_back(_dnaCurrentStn);
}

// DnaXmlFormat_pimpl
//

DnaXmlFormat_pimpl::DnaXmlFormat_pimpl(std::ifstream* is, PUINT32 clusterID, const std::string& referenceframe, const std::string& epoch, 
	bool firstFile, 
	bool userspecifiedreferenceframe, bool userspecifiedepoch,
	bool overridereferenceframe)
{
	// capture pointer to file stream
	is_ = is;
	
	// capture global cluster ID to permit sequential numbering over several input files
	_clusterID = *clusterID;	

	// capture default reference frame and epoch
	_referenceframe = referenceframe;
	_epoch = epoch;

	// Initialise file EPSG and epoch from the default reference frame.
	// Previously these were set by the XSD attribute defaults during
	// validation.  With dont_validate, the attribute parsers are only
	// called when the attributes are present in the XML, so we need
	// sensible fallbacks.
	try {
		_fileEpsg = epsgStringFromName<std::string>(_referenceframe);
	}
	catch (...) {
		_fileEpsg.clear();
	}
	_fileEpoch = epoch;

	// capture first file flag
	_firstFile = firstFile;

	// Has the user supplied a reference frame and should this be used to override all?
	_userspecifiedreferenceframe = userspecifiedreferenceframe;
	_filespecifiedreferenceframe = false;
	_filespecifiedepoch = false;
	_overridereferenceframe = overridereferenceframe;
	_userspecifiedepoch = userspecifiedepoch;
}

void DnaXmlFormat_pimpl::pre()
{
	_pStns = new vdnaStnPtr ;
	_pMsrs = new vdnaMsrPtr ;

	g_parsemsr_tally.initialise();
	g_parsestn_tally.initialise();
	_station_count = 0;
	_measurement_count = 0;
}

void DnaXmlFormat_pimpl::DnaStation()
{
	_station_count++;
}

void DnaXmlFormat_pimpl::DnaMeasurement()
{
}

void DnaXmlFormat_pimpl::type()
{
}

void DnaXmlFormat_pimpl::referenceframe()
{
}

void DnaXmlFormat_pimpl::epoch()
{
}

void DnaXmlFormat_pimpl::post_DnaXmlFormat(vdnaStnPtr* vStations, vdnaMsrPtr* vMeasurements) 
{
	std::ostringstream ss("");
	if (_station_count > 0) 
	{
		ss << "Loaded " << _station_count << " stations";
		_parse_msg = ss.str();
		(*vStations) = (vdnaStnPtr) (*(_pStns));
	}
	if (_measurement_count > 0) 
	{
		ss << "Loaded " << _measurement_count << " measurements";
		_parse_msg = ss.str();
		(*vMeasurements) = (vdnaMsrPtr) (*(_pMsrs));
	}
}

// GPSBaseline_pimpl
//

void GPSBaseline_pimpl::pre()
{
	_dnaGpsBaseline.reset(new CDnaGpsBaseline);
	_dnaGpsBaseline->SetType(_parent_dnaGpsBaselineCluster->GetType());
	_dnaGpsBaseline->SetFirst(_parent_dnaGpsBaselineCluster->GetFirst());
	_dnaGpsBaseline->SetTarget(_parent_dnaGpsBaselineCluster->GetTarget());
	
	_dnaGpsBaseline->SetReferenceFrame(_parent_dnaGpsBaselineCluster->GetReferenceFrame());
	_dnaGpsBaseline->SetEpoch(_parent_dnaGpsBaselineCluster->GetEpoch()); 
	
	_dnaGpsBaseline->SetClusterID(_parent_dnaGpsBaselineCluster->GetClusterID());

	_dnaGpsBaseline->SetClusterDBID(
		_parent_dnaGpsBaselineCluster->GetClusterDBID(),
		_parent_dnaGpsBaselineCluster->GetClusterDBIDset());
	
	if (_parent_dnaGpsBaselineCluster->GetType().empty())
		throw XMLInteropException("\"Type\" element must be provided before \"GPSBaseline\" element.", 0);

	// Is this a 'G' measurement
	if (_parent_dnaGpsBaselineCluster->GetTypeC() != 'X')
		return;

	const UINT32 measCount = _parent_dnaGpsBaselineCluster->GetTotal();

	// Only one baseline?  If so, no co-variances exist.
	// Two or more baselines?  Then reserve co-variance vector
	if (measCount > 1)
		_dnaGpsBaseline->ReserveGpsCovariancesCount(measCount - 1);

}

void GPSBaseline_pimpl::X(const ::std::string& X)
{
	if (_dnaGpsBaseline)
		_dnaGpsBaseline->SetX(X);

	// increment measurement counter
	*(_pMeasurementCount) += 1;

	switch (_dnaGpsBaseline->GetTypeC())
	{
	case 'G':
		g_parsemsr_tally.G++;
		break;
	case 'X':
		g_parsemsr_tally.X++;
		break;
	}
}

void GPSBaseline_pimpl::Y(const ::std::string& Y)
{
	if (_dnaGpsBaseline)
		_dnaGpsBaseline->SetY(Y);

	// increment measurement counter
	*(_pMeasurementCount) += 1;

	switch (_dnaGpsBaseline->GetTypeC())
	{
	case 'G':
		g_parsemsr_tally.G++;
		break;
	case 'X':
		g_parsemsr_tally.X++;
		break;
	}
}

void GPSBaseline_pimpl::Z(const ::std::string& Z)
{
	if (_dnaGpsBaseline)
		_dnaGpsBaseline->SetZ(Z);

	// increment measurement counter
	*(_pMeasurementCount) += 1;

	switch (_dnaGpsBaseline->GetTypeC())
	{
	case 'G':
		g_parsemsr_tally.G++;
		break;
	case 'X':
		g_parsemsr_tally.X++;
		break;
	}
}

void GPSBaseline_pimpl::MeasurementDBID(const ::std::string& MeasurementID)
{
	_dnaGpsBaseline->SetMeasurementDBID(MeasurementID);
}

void GPSBaseline_pimpl::SigmaXX(const ::std::string& SigmaXX)
{
	_dnaGpsBaseline->SetSigmaXX(SigmaXX);
}

void GPSBaseline_pimpl::SigmaXY(const ::std::string& SigmaXY)
{
	_dnaGpsBaseline->SetSigmaXY(SigmaXY);
}

void GPSBaseline_pimpl::SigmaXZ(const ::std::string& SigmaXZ)
{
	_dnaGpsBaseline->SetSigmaXZ(SigmaXZ);
}

void GPSBaseline_pimpl::SigmaYY(const ::std::string& SigmaYY)
{
	_dnaGpsBaseline->SetSigmaYY(SigmaYY);
}

void GPSBaseline_pimpl::SigmaYZ(const ::std::string& SigmaYZ)
{
	_dnaGpsBaseline->SetSigmaYZ(SigmaYZ);
}

void GPSBaseline_pimpl::SigmaZZ(const ::std::string& SigmaZZ)
{
	_dnaGpsBaseline->SetSigmaZZ(SigmaZZ);
}

void GPSBaseline_pimpl::GPSCovariance()
{
}

void GPSBaseline_pimpl::post_GPSBaseline()
{
	if (_dnaGpsBaseline && _parent_dnaGpsBaselineCluster)
		_parent_dnaGpsBaselineCluster->AddGpsBaseline(
		_dnaGpsBaseline.get());
}

// GPSCovariance_pimpl
//

void GPSCovariance_pimpl::pre()
{
	_dnaGpsCovariance.reset(new CDnaCovariance);
	_dnaGpsCovariance->SetType("X");
	_dnaGpsCovariance->SetClusterID(_parent_dnaGpsBaseline->GetClusterID());
}

void GPSCovariance_pimpl::m11(const ::std::string& m11)
{
	_dnaGpsCovariance->SetM11(m11);
}

void GPSCovariance_pimpl::m12(const ::std::string& m12)
{
	_dnaGpsCovariance->SetM12(m12);
}

void GPSCovariance_pimpl::m13(const ::std::string& m13)
{
	_dnaGpsCovariance->SetM13(m13);
}

void GPSCovariance_pimpl::m21(const ::std::string& m21)
{
	_dnaGpsCovariance->SetM21(m21);
}

void GPSCovariance_pimpl::m22(const ::std::string& m22)
{
	_dnaGpsCovariance->SetM22(m22);
}

void GPSCovariance_pimpl::m23(const ::std::string& m23)
{
	_dnaGpsCovariance->SetM23(m23);
}

void GPSCovariance_pimpl::m31(const ::std::string& m31)
{
	_dnaGpsCovariance->SetM31(m31);
}

void GPSCovariance_pimpl::m32(const ::std::string& m32)
{
	_dnaGpsCovariance->SetM32(m32);
}

void GPSCovariance_pimpl::m33(const ::std::string& m33)
{
	_dnaGpsCovariance->SetM33(m33);
}

void GPSCovariance_pimpl::post_GPSCovariance()
{
	if (_dnaGpsCovariance && _parent_dnaGpsBaseline)
		_parent_dnaGpsBaseline->AddGpsCovariance(
		_dnaGpsCovariance.get());
}

// Height_pimpl
//

void Height_pimpl::pre()
{
}

void Height_pimpl::system(const ::std::string& system)
{
	_parent_dnaStn->SetHeightSystem(system);
}

void Height_pimpl::post_Height ()
{
	_parent_dnaStn->SetHeight(post_string());
}

// PointCovariance_pimpl
//

void PointCovariance_pimpl::pre()
{
	_dnaPointCovariance.reset(new CDnaCovariance);
	_dnaPointCovariance->SetType("Y");
	_dnaPointCovariance->SetClusterID(_parent_dnaGpsPoint->GetClusterID());
}

void PointCovariance_pimpl::m11(const ::std::string& m11)
{
	_dnaPointCovariance->SetM11(m11);
}

void PointCovariance_pimpl::m12(const ::std::string& m12)
{
	_dnaPointCovariance->SetM12(m12);
}

void PointCovariance_pimpl::m13(const ::std::string& m13)
{
	_dnaPointCovariance->SetM13(m13);
}

void PointCovariance_pimpl::m21(const ::std::string& m21)
{
	_dnaPointCovariance->SetM21(m21);
}

void PointCovariance_pimpl::m22(const ::std::string& m22)
{
	_dnaPointCovariance->SetM22(m22);
}

void PointCovariance_pimpl::m23(const ::std::string& m23)
{
	_dnaPointCovariance->SetM23(m23);
}

void PointCovariance_pimpl::m31(const ::std::string& m31)
{
	_dnaPointCovariance->SetM31(m31);
}

void PointCovariance_pimpl::m32(const ::std::string& m32)
{
	_dnaPointCovariance->SetM32(m32);
}

void PointCovariance_pimpl::m33(const ::std::string& m33)
{
	_dnaPointCovariance->SetM33(m33);
}

void PointCovariance_pimpl::post_PointCovariance()
{
	if (_dnaPointCovariance && _parent_dnaGpsPoint)
		_parent_dnaGpsPoint->AddPointCovariance(
		_dnaPointCovariance.get());
}

// StationCoord_pimpl
//

void StationCoord_pimpl::pre()
{
}

void StationCoord_pimpl::Name(const ::std::string& /*Name*/)
{
	//_parent_dnaStn->SetName(Name);
}

void StationCoord_pimpl::XAxis(const ::std::string& XAxis)
{
	_parent_dnaStn->SetXAxis(XAxis);
}

void StationCoord_pimpl::YAxis(const ::std::string& YAxis)
{
	_parent_dnaStn->SetYAxis(YAxis);
}

void StationCoord_pimpl::Height(const ::std::string& Height)
{
	_parent_dnaStn->SetHeight(Height);
}

void StationCoord_pimpl::HemisphereZone(const ::std::string& HemisphereZone)
{
	_parent_dnaStn->SetHemisphereZone(HemisphereZone);
}

void StationCoord_pimpl::GeoidModel()
{
}



// GeoidModel_pimpl
//

void GeoidModel_pimpl::pre()
{
}

void GeoidModel_pimpl::NValue (const ::std::string& /*NValue*/)
{

}

void GeoidModel_pimpl::DeflPM (const ::std::string& /*DeflPM*/)
{

}

void GeoidModel_pimpl::DeflPV (const ::std::string& /*DeflPV*/)
{

}

void GeoidModel_pimpl::post_GeoidModel()
{
}

void StationCoord_pimpl::post_StationCoord()
{
}

// type_pimpl
//

void type_pimpl::pre()
{
}

void type_pimpl::post_type()
{
	//const ::std::string& v(post_string());
}

// referenceframe_pimpl
//

void referenceframe_pimpl::pre()
{
	
}

// Note that if the DnaXmlFormat element in the XML file does not contain an
// attribute named referenceframe, the default will be set to whatever is in
// the XSD file.
// For DynaML.xsd, the following is specified:
//     <xs:attribute name="referenceframe" type="xs:string" use="optional" default="GDA2020"/>
// In this case, post_string() will return "GDA2020"
void referenceframe_pimpl::post_type(std::string& referenceframe, std::string& fileEpsg,
	bool userspecifiedreferenceframe, bool firstFile)
{
	// 1. Get the DnaXmlFormat referenceframe attribute value from the file
	_referenceframe = trimstr(post_string());

	// But, is this attribute value an empty string?  As long as a default value 
	// is specified in DynaML.xsd, this value will never be empty, unless the user
	// has inadvertently set in the xml file, e.g.:
	//  <DnaXmlFormat referenceframe="" >
	// Check anyway ...
	if (_referenceframe.empty())
		// If the file doesn't contain reference frame, set
		// to the default reference frame passed from import
		_referenceframe = referenceframe;

	try {
		// Capture epsg code for the file
		fileEpsg = epsgStringFromName<std::string>(_referenceframe);
	}
	catch (std::runtime_error& e) {
		std::stringstream ss("");
		ss << e.what() << std::endl;
		throw XMLInteropException(ss.str(), 0);
	}

	if (!userspecifiedreferenceframe)
	{
		// No frame supplied. Set the datum from the first file. 
		// If the datum field is blank in the first file, the default will be used. 
		if (firstFile)
			referenceframe = _referenceframe;
	}
}

// epoch_pimpl
//

void epoch_pimpl::pre()
{
}

// Note that if the DnaXmlFormat element in the XML file does not contain an
// attribute named epoch, the default will be set to whatever is in the XSD file.
// For DynaML.xsd, the following is specified:
//     <xs:attribute name="epoch" type="xs:string" use="optional" default="01.01.1994"/>
// In this case, post_string() will return "01.01.1994"
void epoch_pimpl::post_type(std::string& epoch, std::string& fileEpoch,
	bool userspecifiedreferenceframe, bool userspecifiedepoch, 
	bool firstFile)
{
	// 1. Get the DnaXmlFormat epoch attribute value from the file
	_epoch = trimstr(post_string());
	
	// But, is this attribute value an empty string?  As long as a default value 
	// is specified in DynaML.xsd, this value will never be empty, unless the user
	// has inadvertently set in the xml file, e.g.:
	//  <DnaXmlFormat epoch="" >
	// Check anyway ...
	if (_epoch.empty())
		// Set to the default epoch passed from import
		_epoch = epoch;

	// Capture epoch for the file
	fileEpoch = _epoch;

	// Set the epoch, provided the user does not want to 
	// override all epoch information
	// Note, epoch is contingent upon how the frame has been
	// supplied
	if (userspecifiedreferenceframe)
	{
		// A frame has been supplied. Now check for epoch.

		// Has the user supplied an epoch on the command line (--epoch)?
		if (!userspecifiedepoch)
		{
			// No epoch supplied. Take the epoch from the first file.
			if (firstFile)
				// If the user didn't specify a frame, take it from the file
				epoch = _epoch;
		}

	}
	else
	{
		// No frame supplied. Set the datum from the first file. 
		// If the datum field is blank in the first file, the default will be used. 
		if (firstFile)
			epoch = _epoch;
	}
}

// system_pimpl
//

void system_pimpl::pre()
{
}

void system_pimpl::post_system ()
{
	const ::std::string& v (post_string());

}
