# Test script 

# See URLs at https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml

name: Testing

on:
  workflow_dispatch:

env:
  VCPKG_PACKAGES: xerces-c:x86-windows-static curl:x86-windows-static

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Set number of cores
        shell: bash
        run: |
          WMIC CPU Get -Format:List
          WMIC CPU Get NumberOfLogicalProcessors | head -2 | tail -1 > ncores
          echo "NCORES=$(cat ncores)" >> $GITHUB_ENV
          echo "VCPKG_MAX_CONCURRENCY=$(cat ncores)" >> $GITHUB_ENV

      - name: Hash vcpkg package names
        shell: bash
        run: |
          echo VCPKG_HASH=$(echo "${VCPKG_PACKAGES}" | sed "s/ /_/g" | md5sum | cut -f 1 -d" ") >> $GITHUB_ENV

      - name: Print GitHub environment
        shell: bash
        run: |
          cat $GITHUB_ENV >&2
    
      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ./vcpkg/vcpkg.exe
            ./vcpkg/installed
            # ./vcpkg/downloads
          key: ${{ runner.os }}-${{ env.VCPKG_HASH }}

      - name: Prepare vcpkg
        shell: powershell
        run: |
          # https://learn.microsoft.com/en-us/vcpkg/get_started/get-started?pivots=shell-powershell#1---set-up-vcpkg
          if (-not (Test-Path './vcpkg/vcpkg.exe')) {
            git clone https://github.com/microsoft/vcpkg ./vcpkg
            ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
          } else {
            Write-Host "vcpkg.exe already exists; skipping bootstrap."
          }
          
      - name: Install vcpkg prerequisites
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          echo Installing packages: %VCPKG_PACKAGES%
          .\vcpkg\vcpkg.exe install %VCPKG_PACKAGES% --triplet=x64-windows
      
      - name: List installed packages
        shell: cmd
        run: |
          .\vcpkg\vcpkg.exe list

      - name: Integrate vpkg
        shell: cmd
        run: |
          .\vcpkg\vcpkg.exe integrate install
